# Generated by Django 4.0.5 on 2022-08-29 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='measurement',
            name='id_sensor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
